### ISSUE TITLE
Consul invalid duration error

### ISSUE THREAD

**Issue by adriananeci** [YotpoLtd/resec#27]
When using resec (v0.5.1) with consul 1.4.1  I'm getting a lot of errors like:
```time="2019-02-01T15:58:01Z" level=error msg="Consul error: time: invalid duration " system=consul```
```message repeated 18 times: [ time="2019-02-01T15:58:01Z" level=error msg="Consul error: time: invalid duration " system=consul]```
Maybe there were some breaking changes done in consul api in 1.4.x version.
Also I've noticed that the resec version is a hard-coded string (x.y.z). Maybe it will be a good idea to add the right version to make bug reporting more accurate.

**Comment by burdandrei** [comment]
@adriananeci could you please check this behaviour in 0.6?

**Comment by adriananeci** [comment]
Hi @burdandrei,

PR for resec 0.6 release is still opened as I can see.
Anyway , I've managed to solve this issue by changing MASTER_TAGS and SLAVE_TAGS values.
I think we can close this issue.
